export { default as settingTable } from './settingTable/settingTable.vue'                    // 表格
export { default as settingTableAction } from './settingTableAction/settingTableAction.vue'  // 表格操作栏
export { default as settingQuery } from './settingQuery/settingQuery.vue'                    // 搜素栏
export { default as settingDialogAdd } from './settingDialogAdd/settingDialogAdd.vue'        // 新增对话框
export { default as settingDialogEdit } from './settingDialogEdit/settingDialogEdit.vue'     // 编辑对话框
export { default as settingDialogRead } from './settingDialogRead/settingDialogRead.vue'     // 查看对话框
export { default as settingAction } from './settingAction/settingAction.vue'                 // 操作栏
export { default as settingBatchAction } from './settingBatchAction/settingBatchAction.vue'  // 批量操作
export { default as settingPagination } from './settingPagination/settingPagination.vue'     // 分页